version: "3.8"

services:
  db:
    hostname: db
    image: postgres
    ports:
      - 8888:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    environment:
      - SEU_PORTFOLIO_REGISTRYAPI_PORT=8080
      - SEU_PORTFOLIO_REGISTRYAPI_APP_NAME=registryapi
      - SEU_PORTFOLIO_REGISTRYAPI_DB_HOSTNAME=db
      - SEU_PORTFOLIO_REGISTRYAPI_DB_PORT=5432
      - SEU_PORTFOLIO_REGISTRYAPI_DB_PATH=db
      - SEU_PORTFOLIO_REGISTRYAPI_DB_USERNAME=postgres
      - SEU_PORTFOLIO_REGISTRYAPI_DB_PASSWORD=password
      - SEU_PORTFOLIO_REGISTRYAPI_ACCESS_TOKEN_SECRET=test
      - SEU_PORTFOLIO_REGISTRYAPI_ACCESS_TOKEN_EXP=5
      - SEU_PORTFOLIO_REGISTRYAPI_REFRESH_TOKEN_SECRET=test
      - SEU_PORTFOLIO_REGISTRYAPI_REFRESH_TOKEN_EXP=24
      - SEU_PORTFOLIO_REGISTRYAPI_REFRESH_TOKEN_SECURE=true
      - SEU_PORTFOLIO_REGISTRYAPI_REFRESH_TOKEN_DOMAIN=localhost
      - SEU_PORTFOLIO_REGISTRYAPI_REFRESH_TOKEN_HTTP_ONLY=true
      - SEU_PORTFOLIO_REGISTRYAPI_SHOW_SQL=true
      - SEU_PORTFOLIO_REGISTRYAPI_EXPOSE_HEALTH=health

volumes:
  db:
    driver: local
